// <auto-generated />
namespace FilmoweJanusze.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserRate_UserId_changeto_UserID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserRate_UserId_changeto_UserID));
        
        string IMigrationMetadata.Id
        {
            get { return "201901301245455_UserRate_UserId_changeto_UserID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
